---
- name: Build the Ubuntu Plex server
  hosts: localhost
  gather_facts: true
  become: yes

  tasks:
  - name: install vim
    apt: name=vim state=present
  
  - name: install open-ssh
    apt: name=openssh-server state=present

  - name: install git
    apt: name=git state=present
    
 # sudo wget https://ocean.surfshark.com/debian/pool/main/s/surfshark-release/surfshark-release_1.0.0-2_amd64.deb
 # sudo dpkg -i surfshark-release_1.0.0-2_amd64.deb
 # sudo apt-get install surfshark-vpn
 #
 #
 #
 #
