---
    - name: Copy .bashrc file
      copy:
        src: files/bashprompt/.bashrc
        dest: "{{ ansible_env['HOME'] }}/.bashrc"
        owner: "{{ ansible_env['LOGNAME'] }}"
        group: "{{ ansible_env['LOGNAME'] }}"
        mode: '0700'

    - name: Copy bash-git-prompt files
      copy:
        src: files/bashprompt/.bash-git-prompt/
        dest: "{{ ansible_env['HOME'] }}.bash-git-prompt/"
        owner: "{{ ansible_env['LOGNAME'] }}"
        group: "{{ ansible_env['LOGNAME'] }}"
        mode: '0700'

    - name: Copy bash auto completion files
      copy:
        src: files/bashprompt/bash_completion.d
        dest: /etc/bash_completion.d
        owner: "{{ ansible_env['LOGNAME'] }}"
        group: "{{ ansible_env['LOGNAME'] }}"
        mode: '0700'

    - name: Copy flamel container wrapper script
      copy:
        src: files/flamelc/flamel.sh
        dest: "/home/{{ devuser }}/.local/bin/"
        owner: "{{ ansible_env['LOGNAME'] }}"
        group: "{{ ansible_env['LOGNAME'] }}"
        mode: '0700'

    - name: Copy .vimrc file
      copy:
        src: files/vim/.vimrc
        dest: "/home/{{ devuser }}/"
        owner: "{{ ansible_env['LOGNAME'] }}"
        group: "{{ ansible_env['LOGNAME'] }}"
        mode: '0700'

    - name: Copy vim plugin files
      synchronize:
        src: files/vim/.vim/
        dest: "{{ ansible_env['HOME'] }}/.vim/"
        owner: "{{ ansible_env['LOGNAME'] }}"
        group: "{{ ansible_env['LOGNAME'] }}"
        #mode: '0700'

#    - name: Ensure podman is started
#      service:
#        name: podman
#        state: started
#        enabled: true
#
#    - name: Install curriculum dev packages
#      package:
#        name: "{{ packages }}"
#        state: latest